# Generated by Django 4.0.3 on 2022-05-17 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='ref',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[(0, 'pending'), (1, 'approved'), (2, 'declined')], default=0, max_length=2),
        ),
    ]
