# Generated by Django 4.0.3 on 2022-05-17 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_transaction_ref_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[(0, 'USSD'), (1, 'Card')], default=0, max_length=2),
            preserve_default=False,
        ),
    ]
