# Generated by Django 4.0.3 on 2022-05-17 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_block_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='date',
            field=models.DateField(auto_now_add=True, unique=True),
        ),
    ]
