# Generated by Django 4.0.3 on 2022-05-19 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_job_job_type_alter_job_status'),
        ('finance', '0005_alter_block_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='job',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_info', to='customer.job'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('0', 'USSD'), ('1', 'Card')], max_length=2),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('0', 'pending'), ('1', 'approved'), ('2', 'declined')], default='0', max_length=2),
        ),
    ]
