# Generated by Django 4.0.3 on 2022-05-19 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankInformations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(choices=[('uba', 'UBA'), ('fcmb', 'FCMB'), ('sterling', 'STERLING BANK'), ('kuda', 'KUDA MFB'), ('gtb', 'GTB')], max_length=20)),
                ('account_name', models.CharField(max_length=25)),
                ('account_number', models.CharField(max_length=14)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_infos', to='core.site')),
            ],
        ),
    ]
