# Generated by Django 4.0.3 on 2022-05-03 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_job_job_type_alter_job_price_per_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='copies',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='photo',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exposures', to='customer.job'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
