# Generated by Django 4.0.3 on 2022-05-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_photo_copies_alter_photo_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='copies',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
