# Generated by Django 4.0.3 on 2022-05-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_remove_job_job_type_remove_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[(0, '4x6'), (1, '5x7'), (2, '8x10')], default=1, max_length=2),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[(0, 'booking'), (1, 'processing'), (2, 'completed')], default=0, max_length=2),
        ),
    ]
